add a method to get only the instantiation queried
rather than default behavior of returning all of the related asset's
instantiations for the instantiation queried

diff --git a/pbprotracktor b/pbprotracktor
--- a/pbprotracktor
+++ b/pbprotracktor
@@ -22,6 +22,17 @@ if [[ -z "$PROTRACK_DB_URL" || -z "$PROTRACK_DB_USER" ]] ; then
     exit 1
 fi
 
+OPTIND=1
+while getopts ":cah" OPT ; do
+    case "${OPT}" in
+        a) ALL_INST="Y" ;;
+        *) echo "bad option -${OPTARG}" ; _usage ;;
+        :) echo "Option -${OPTARG} requires an argument" ; _writeerrorlog "makebroadcast" "The option selected required an argument and none was provided. The script had to exit." ; exit 1 ;;
+    esac
+done
+shift $(( ${OPTIND} - 1 ))
+
+if [[ "${ALL_INST}" == "Y" ]] ; then
     INSTANTIATION_CALL="(SELECT XMLAGG (
                         XMLELEMENT(NAME \"pbcoreInstantiation\",
                             XMLELEMENT(NAME \"instantiationIdentifier\",
@@ -69,6 +80,56 @@ fi
                         ) ORDER BY li_material_id ASC)
                     FROM linkinfo WHERE linkinfo.li_vsn_id = quad_tab.vsn_serial
                     )"
+else
+    INSTANTIATION_CALL="(SELECT XMLAGG (
+                        XMLELEMENT(NAME \"pbcoreInstantiation\",
+                            XMLELEMENT(NAME \"instantiationIdentifier\",
+                                XMLATTRIBUTES('li_serial' as \"source\"),
+                                li_serial),
+                            XMLELEMENT(NAME \"instantiationIdentifier\",
+                                XMLATTRIBUTES('Media ID' as \"source\"),
+                                trim(li_material_id)),
+                            CASE WHEN li_cart_id is not null THEN
+                            XMLELEMENT(NAME \"instantiationIdentifier\",
+                                XMLATTRIBUTES('Cart ID' as \"source\"),
+                                trim(li_cart_id))
+                            END,
+                            XMLELEMENT(NAME \"instantiationDate\",
+                                XMLATTRIBUTES('availableStart' as \"dateType\"),
+                                li_start_date),
+                            XMLELEMENT(NAME \"instantiationDate\",
+                                XMLATTRIBUTES(
+                                    'availableEnd' as \"dateType\",
+                                    ':-/' as \"annotation\"
+                                ),
+                                li_end_date),
+                            XMLELEMENT(NAME \"instantiationLocation\"),
+                            XMLELEMENT(NAME \"instantiationTimeStart\",li_in_char),
+                            XMLELEMENT(NAME \"instantiationDuration\",li_length_char),
+                            CASE WHEN li_use_for_air = 0 THEN
+                                XMLELEMENT(NAME \"instantiationAnnotation\",
+                                    XMLATTRIBUTES('accessRestriction' as \"annotationType\"),
+                                    'Restricted')
+                            END,
+                            CASE WHEN li_cart_id is not null THEN
+                                XMLELEMENT(NAME \"instantiationAnnotation\",
+                                    XMLATTRIBUTES('accessRestriction' as \"annotationType\"),
+                                    'Restricted')
+                            END,
+                            (SELECT
+                                CASE WHEN string_agg(no_text,' ') is not null THEN
+                                    XMLELEMENT(NAME \"instantiationAnnotation\",
+                                        XMLATTRIBUTES('Technical Notes' as \"annotationType\"),
+                                        trim(string_agg(no_text,' ' ORDER BY no_sequence ASC)))
+                                END
+                            FROM notes
+                            WHERE notes.no_parent = li_serial AND notes.no_location = 'tapelink'
+                            )
+                        ) ORDER BY li_material_id ASC)
+                    FROM linkinfo WHERE linkinfo.li_vsn_id = quad_tab.vsn_serial AND linkinfo.li_material_id IN ( $(printf "'%s'," "$@" | sed 's/,$//') )
+                    )"
+fi
+
 _getpbcore(){
 psql -Ath "$PROTRACK_DB_URL" -U "$PROTRACK_DB_USER" -d protrack -c "\
     SELECT
