tiny stylistic changes

diff --git a/prot2rs b/prot2rs
--- a/prot2rs
+++ b/prot2rs
@@ -24,16 +24,22 @@ PBCORE_INSTANTIATION_FIELD=116
 LAST_UPDATED_FIELD=109
 
 _usage(){
-    echo
-    echo "$(basename "${0}")"
-    echo "Query ProTrack with pbprotracktor to gather PBCore data, transform it, and push it to ResourceSpace."
-    echo "Usage: $(basename "${0}") [ -d /path/to/deliver/to/ ] fileorpackage1 [ fileorpackage2 ...]"
-    echo "  -F DATE or Negative Integer (update ResourceSpace's records updated after the DATE provided (in YYYY-MM-DD form) or provide a negative number to update records updated within the past number of specified days)"
-    echo "  -f DATE or Negative Integer (update ProTrack's records updated after the DATE provided (in YYYY-MM-DD form) or provide a negative number to update records updated within the past number of specified days)"
-    echo "  -t ( sets up a featured collection based on today's date )"
-    echo "  -h ( display this help )"
-    echo
-exit
+    cat <<EOF
+$(basename "${0}")
+Query ProTrack with pbprotracktor to gather PBCore data, transform it, and push
+it to ResourceSpace.
+
+Usage: $(basename "${0}") [ -d /path/to/deliver/to/ ] {fileorpackage}
+  -F  DATE or Negative Integer (update ResourceSpace's records updated after
+      the DATE provided (in YYYY-MM-DD form) or provide a negative number to
+      update records updated within the past number of specified days)
+  -f  DATE or Negative Integer (update ProTrack's records updated after the
+      DATE provided (in YYYY-MM-DD form) or provide a negative number to update
+      records updated within the past number of specified days)
+  -t  sets up a featured collection based on today's date
+  -h  display this help
+EOF
+    exit
 }
 
 urlencode() {
@@ -216,15 +222,15 @@ if [ ! -f "${CONF_FILE}" ] ; then
     exit 1
 fi
 
-. "${CONF_FILE}" || { echo "Missing ${CONF_FILE}. Exiting." ; exit 1 ;};
+. "${CONF_FILE}" || { echo "Missing ${CONF_FILE}. Exiting." ; exit 1 ; }
 
 OPTIND=1
 while getopts ":f:F:th" OPT ; do
     case "${OPT}" in
-        f) FROM_DATE_PT="${OPTARG}";;
-        F) FROM_DATE_RS="${OPTARG}";;
-        t) MAKETODAY="Y";;
-        h) _usage;;
+        f) FROM_DATE_PT="${OPTARG}" ;;
+        F) FROM_DATE_RS="${OPTARG}" ;;
+        t) MAKETODAY="Y" ;;
+        h) _usage ;;
         :) echo "Option -${OPTARG} requires an argument" ; _writeerrorlog "makeyoutube" "The option selected required an argument and none was provided. The script had to exit." ; exit 1 ;;
         *) echo "bad option -${OPTARG}" ; _usage ;;
     esac
